apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: exemplo-external-service
spec:
  selector:
    role: exemplo-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer